"""create initial tables

Revision ID: c0d75c6a8e88
Revises: 
Create Date: 2026-01-06 10:34:02.186730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d75c6a8e88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('global_event_id', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('event_root_code', sa.String(length=2), nullable=False),
    sa.Column('event_base_code', sa.String(length=4), nullable=True),
    sa.Column('event_code', sa.String(length=10), nullable=True),
    sa.Column('actor1_code', sa.String(length=10), nullable=True),
    sa.Column('actor1_name', sa.String(length=255), nullable=True),
    sa.Column('actor1_country_code', sa.String(length=3), nullable=True),
    sa.Column('actor1_type', sa.String(length=3), nullable=True),
    sa.Column('actor2_code', sa.String(length=10), nullable=True),
    sa.Column('actor2_name', sa.String(length=255), nullable=True),
    sa.Column('actor2_country_code', sa.String(length=3), nullable=True),
    sa.Column('actor2_type', sa.String(length=3), nullable=True),
    sa.Column('is_root_event', sa.Boolean(), nullable=True),
    sa.Column('goldstein_scale', sa.Float(), nullable=True),
    sa.Column('num_mentions', sa.Integer(), nullable=True),
    sa.Column('num_sources', sa.Integer(), nullable=True),
    sa.Column('num_articles', sa.Integer(), nullable=True),
    sa.Column('avg_tone', sa.Float(), nullable=True),
    sa.Column('action_geo_country_code', sa.String(length=3), nullable=True),
    sa.Column('action_geo_name', sa.String(length=255), nullable=True),
    sa.Column('action_geo_lat', sa.Float(), nullable=True),
    sa.Column('action_geo_long', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_action_geo_country_code'), 'events', ['action_geo_country_code'], unique=False)
    op.create_index(op.f('ix_events_actor1_code'), 'events', ['actor1_code'], unique=False)
    op.create_index(op.f('ix_events_actor1_country_code'), 'events', ['actor1_country_code'], unique=False)
    op.create_index(op.f('ix_events_actor2_code'), 'events', ['actor2_code'], unique=False)
    op.create_index(op.f('ix_events_actor2_country_code'), 'events', ['actor2_country_code'], unique=False)
    op.create_index('ix_events_actors', 'events', ['actor1_country_code', 'actor2_country_code'], unique=False)
    op.create_index('ix_events_date_code', 'events', ['event_date', 'event_root_code'], unique=False)
    op.create_index('ix_events_date_country', 'events', ['event_date', 'action_geo_country_code'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_event_root_code'), 'events', ['event_root_code'], unique=False)
    op.create_index(op.f('ix_events_global_event_id'), 'events', ['global_event_id'], unique=True)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('log_return', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_market_data_symbol_date')
    )
    op.create_index(op.f('ix_market_data_date'), 'market_data', ['date'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index('ix_market_data_symbol_date', 'market_data', ['symbol', 'date'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('analysis_type', sa.String(length=30), nullable=False),
    sa.Column('car', sa.Float(), nullable=True),
    sa.Column('car_t_stat', sa.Float(), nullable=True),
    sa.Column('car_p_value', sa.Float(), nullable=True),
    sa.Column('estimation_window_start', sa.Date(), nullable=True),
    sa.Column('estimation_window_end', sa.Date(), nullable=True),
    sa.Column('event_window_start', sa.Date(), nullable=True),
    sa.Column('event_window_end', sa.Date(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('abnormal_return', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=30), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'symbol', 'analysis_type', name='uq_analysis_result')
    )
    op.create_index('ix_analysis_anomalies', 'analysis_results', ['is_anomaly', 'is_significant'], unique=False)
    op.create_index('ix_analysis_event_symbol', 'analysis_results', ['event_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_analysis_results_is_anomaly'), 'analysis_results', ['is_anomaly'], unique=False)
    op.create_index(op.f('ix_analysis_results_is_significant'), 'analysis_results', ['is_significant'], unique=False)
    op.create_index(op.f('ix_analysis_results_symbol'), 'analysis_results', ['symbol'], unique=False)
    op.create_table('event_market_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('market_data_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_data_id'], ['market_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'market_data_id', name='uq_event_market_link')
    )
    op.create_index('ix_event_market_link_event', 'event_market_links', ['event_id'], unique=False)
    op.create_index('ix_event_market_link_market', 'event_market_links', ['market_data_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_market_link_market', table_name='event_market_links')
    op.drop_index('ix_event_market_link_event', table_name='event_market_links')
    op.drop_table('event_market_links')
    op.drop_index(op.f('ix_analysis_results_symbol'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_is_significant'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_is_anomaly'), table_name='analysis_results')
    op.drop_index('ix_analysis_event_symbol', table_name='analysis_results')
    op.drop_index('ix_analysis_anomalies', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index('ix_market_data_symbol_date', table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_date'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_events_global_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_root_code'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index('ix_events_date_country', table_name='events')
    op.drop_index('ix_events_date_code', table_name='events')
    op.drop_index('ix_events_actors', table_name='events')
    op.drop_index(op.f('ix_events_actor2_country_code'), table_name='events')
    op.drop_index(op.f('ix_events_actor2_code'), table_name='events')
    op.drop_index(op.f('ix_events_actor1_country_code'), table_name='events')
    op.drop_index(op.f('ix_events_actor1_code'), table_name='events')
    op.drop_index(op.f('ix_events_action_geo_country_code'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
