"""Add correlation_cache table

Revision ID: fb13caaa6309
Revises: c0d75c6a8e88
Create Date: 2026-02-19 12:55:52.177700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb13caaa6309'
down_revision: Union[str, Sequence[str], None] = 'c0d75c6a8e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('event_metric', sa.String(length=30), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'event_metric', 'method', name='uq_correlation_cache')
    )
    op.create_index(op.f('ix_correlation_cache_symbol'), 'correlation_cache', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correlation_cache_symbol'), table_name='correlation_cache')
    op.drop_table('correlation_cache')
    # ### end Alembic commands ###
